# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
 adapter: mysql2
 database: library_development
 username: root
 password:
 host: localhost
test:
 adapter: mysql2
 database: library_test
 username: root
 password:
 host: localhost
production:
 adapter: mysql2
 database: library_production
 username: root
 password:
 host: localhost
